WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/root/miniconda3/envs/medsam2/bin/python: can't open file '/root/prostate-check-zjz/Test-model/./training/train.py': [Errno 2] No such file or directory
/root/miniconda3/envs/medsam2/bin/python: can't open file '/root/prostate-check-zjz/Test-model/./training/train.py': [Errno 2] No such file or directory
E0205 15:49:58.739000 140254697247936 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 55688) of binary: /root/miniconda3/envs/medsam2/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/miniconda3/envs/medsam2/lib/python3.12/site-packages/torch/distributed/run.py", line 905, in <module>
    main()
  File "/root/miniconda3/envs/medsam2/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/medsam2/lib/python3.12/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/root/miniconda3/envs/medsam2/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/root/miniconda3/envs/medsam2/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/medsam2/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./training/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-02-05_15:49:58
  host      : 5074413677cb
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 55689)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-02-05_15:49:58
  host      : 5074413677cb
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 55688)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
